#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/config.json"
PYTHON="${PYTHON:-python3}"
STAGE="init"
FORCE=0
PRINT_ENV=0
NO_SHORTLINK=0
RUN_QC=0

usage() {
  cat <<'EOF'
Usage: ./pipeline.sh [stage] [--config FILE] [--force] [--qc] [--print-env] [--no-shortlink]

Stages:
  init       Prepare SAS ODF state.
  repro      Run epproc/emproc and write raw EPIC manifests.
  clean      Apply flare GTIs and PPS-style band event filters.
  all        Run init, repro, and clean.
  qc-init    QC init outputs.
  qc-repro   QC repro outputs.
  qc-clean   QC clean outputs.
  qc         Run all implemented QC stages.
  env        Print output/sas_setup.env.

Options:
  --config FILE   JSON config file. Default: ./config.json
  --force         Rebuild stage products.
  --qc            Run matching QC after a production stage.
  --print-env     Print saved SAS environment after init.
  --no-shortlink  Use configured workdir instead of a /tmp shortlink.
EOF
}

while (($#)); do
  case "$1" in
    init|repro|clean|all|qc-init|qc-repro|qc-clean|qc|env) STAGE="$1"; shift ;;
    --config|-c) CONFIG="$2"; shift 2 ;;
    --force|-f) FORCE=1; shift ;;
    --qc) RUN_QC=1; shift ;;
    --print-env) PRINT_ENV=1; shift ;;
    --no-shortlink) NO_SHORTLINK=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

need_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1" >&2; exit 1; }; }
need_file() { [[ -f "$1" ]] || { echo "Missing file: $1" >&2; exit 1; }; }
is_yes() { [[ "${1,,}" == "1" || "${1,,}" == "y" || "${1,,}" == "yes" || "${1,,}" == "true" ]]; }

need_cmd "$PYTHON"
need_file "$SCRIPT_DIR/tools.py"
need_file "$CONFIG"
eval "$("$PYTHON" "$SCRIPT_DIR/tools.py" shell "$CONFIG")"
[[ -n "${DETECTORS:-}" ]] || { echo "No detectors selected" >&2; exit 1; }

REAL_WORKDIR="$WORKDIR"
mkdir -p "$REAL_WORKDIR"

if [[ "$NO_SHORTLINK" != "1" && "${#REAL_WORKDIR}" -gt "$SHORTLINK_MAX_PATH" ]]; then
  SHORTLINK="/tmp/_xmm_${SHORTLINK_NAME:-v6_$$}"
  if [[ -e "$SHORTLINK" && ! -L "$SHORTLINK" ]]; then
    echo "Shortlink path exists and is not a symlink: $SHORTLINK" >&2
    exit 1
  fi
  rm -f "$SHORTLINK"
  ln -sfn "$REAL_WORKDIR" "$SHORTLINK"
  WORKDIR="$SHORTLINK"
  is_yes "$KEEP_SHORTLINK" || trap 'rm -f "$SHORTLINK"' EXIT
fi

INITDIR="$WORKDIR/init"
REAL_INITDIR="$REAL_WORKDIR/init"
REPRODIR="$WORKDIR/repro"
REAL_REPRODIR="$REAL_WORKDIR/repro"
CLEANDIR="$WORKDIR/clean"
REAL_CLEANDIR="$REAL_WORKDIR/clean"
GTIDIR="$CLEANDIR/gti"
LIGHTCURVEDIR="$CLEANDIR/lightcurves"
GTI_SUMMARY="$CLEANDIR/flare_gti_summary.tsv"
LOGDIR="$WORKDIR/logs"
mkdir -p "$INITDIR" "$REPRODIR" "$CLEANDIR" "$LOGDIR"

write_if_changed() {
  local path="$1" tmp
  tmp="${path}.tmp.$$"
  mkdir -p "$(dirname "$path")"
  cat > "$tmp"
  if [[ -e "$path" ]] && cmp -s "$tmp" "$path"; then
    rm -f "$tmp"
  else
    mv -f "$tmp" "$path"
  fi
}

runlog() {
  local name="$1"
  shift
  echo "[$(date -u +%FT%TZ)] $name" | tee -a "$LOGDIR/pipeline.log"
  "$@" 2>&1 | tee "$LOGDIR/${name}.log"
}

source_sas() {
  if command -v sasversion >/dev/null 2>&1 && [[ -n "${SAS_DIR:-}" && -n "${SAS_PATH:-}" ]]; then
    return 0
  fi

  local setup_script="${SAS_SETUP_SCRIPT:-}"
  if [[ -z "$setup_script" && -n "${SAS_DIR:-}" && -f "$SAS_DIR/setsas.sh" ]]; then
    setup_script="$SAS_DIR/setsas.sh"
  fi
  [[ -z "$setup_script" ]] && return 0
  need_file "$setup_script"

  set +e +u
  # shellcheck source=/dev/null
  source "$setup_script"
  local status=$?
  set -euo pipefail
  if [[ "$status" -ne 0 ]]; then
    echo "Failed to source SAS setup script: $setup_script" >&2
    exit "$status"
  fi
}

first_summary() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -maxdepth 1 -type f -name '*SUM.SAS' | sort | head -n 1
}

init_products_ready() {
  local sum
  sum="$(first_summary "$REAL_INITDIR")"
  [[ -s "$REAL_INITDIR/ccf.cif" && -n "$sum" && -s "$sum" ]]
}

mirror_odf_into_init() {
  is_yes "$LINK_ODF_CONSTITUENTS" || return 0
  [[ -d "$ODFDIR" ]] || return 0

  local f base skip pat
  IFS='|' read -r -a SKIP_PATTERNS <<< "$SKIP_ODF_LINK_PATTERNS"
  for f in "$ODFDIR"/*; do
    [[ -f "$f" ]] || continue
    base="$(basename "$f")"
    skip=0
    for pat in "${SKIP_PATTERNS[@]}"; do
      [[ -n "$pat" && "$base" == $pat ]] && { skip=1; break; }
    done
    [[ "$skip" == "1" ]] && continue
    [[ -e "$INITDIR/$base" ]] || ln -sf "$f" "$INITDIR/$base"
  done
}

write_sas_setup() {
  local sum_real="$1" ccfpath verbosity
  ccfpath="${SAS_CCFPATH:-$SAS_CCFPATH_CONFIG}"
  verbosity="${SAS_VERBOSITY:-$SAS_VERBOSITY_CONFIG}"
  {
    echo "# Generated by reduction_v6/pipeline.sh"
    printf 'export SAS_CCF=%q\n' "$REAL_INITDIR/ccf.cif"
    printf 'export SAS_ODF=%q\n' "$sum_real"
    if [[ -n "$ccfpath" ]]; then
      printf 'export SAS_CCFPATH=%q\n' "$ccfpath"
    fi
    if [[ -n "$verbosity" ]]; then
      printf 'export SAS_VERBOSITY=%q\n' "$verbosity"
    fi
  } | write_if_changed "$REAL_WORKDIR/sas_setup.env"
}

adopt_existing_init() {
  local sum
  sum="$(first_summary "$REAL_INITDIR")"
  [[ -s "$REAL_INITDIR/ccf.cif" && -n "$sum" && -s "$sum" ]] || return 1
  mirror_odf_into_init
  "$PYTHON" "$SCRIPT_DIR/tools.py" rewrite-path "$sum" "$REAL_INITDIR/"
  write_sas_setup "$sum"
}

print_env() {
  need_file "$REAL_WORKDIR/sas_setup.env"
  cat "$REAL_WORKDIR/sas_setup.env"
}

set_sas_init_env() {
  export SAS_ODF="$ODFDIR"
  export SAS_CCF="$INITDIR/ccf.cif"
  [[ -n "$SAS_CCFPATH_CONFIG" ]] && export SAS_CCFPATH="$SAS_CCFPATH_CONFIG"
  [[ -n "$SAS_VERBOSITY_CONFIG" ]] && export SAS_VERBOSITY="$SAS_VERBOSITY_CONFIG"
  source_sas

  if [[ -z "${SAS_CCFPATH:-}" ]]; then
    echo "Warning: SAS_CCFPATH is unset; cifbuild may fail without a visible CCF repository." >&2
  fi
}

set_sas_repro_env() {
  need_file "$REAL_WORKDIR/sas_setup.env"
  # shellcheck source=/dev/null
  source "$REAL_WORKDIR/sas_setup.env"
  source_sas

  local sum
  sum="$(first_summary "$INITDIR")"
  [[ -n "$sum" ]] && export SAS_ODF="$sum"
  export SAS_CCF="$INITDIR/ccf.cif"
  need_file "${SAS_CCF:-}"
  need_file "${SAS_ODF:-}"
}

set_sas_clean_env() {
  set_sas_repro_env
  need_file "$REAL_WORKDIR/attitude.env"
  # shellcheck source=/dev/null
  source "$REAL_WORKDIR/attitude.env"
  need_file "${ATTHKGEN_FILE:-}"
}

stage_init() {
  if [[ "$FORCE" == "1" ]]; then
    rm -f "$INITDIR/ccf.cif" "$INITDIR"/*SUM.SAS "$REAL_WORKDIR/sas_setup.env"
  elif adopt_existing_init; then
    echo "Skipping init; found existing ccf.cif and SUM.SAS"
    [[ "$PRINT_ENV" == "1" ]] && print_env
    return 0
  fi

  [[ -d "$ODFDIR" ]] || { echo "ODF directory does not exist: $ODFDIR" >&2; exit 1; }

  set_sas_init_env
  need_cmd cifbuild
  need_cmd odfingest

  pushd "$INITDIR" >/dev/null
  runlog init_cifbuild cifbuild
  export SAS_CCF="$INITDIR/ccf.cif"
  runlog init_odfingest odfingest odfdir="$ODFDIR" outdir="$INITDIR"
  popd >/dev/null

  local sum real_sum
  sum="$(first_summary "$INITDIR")"
  [[ -n "$sum" ]] || { echo "odfingest did not create a *SUM.SAS file in $INITDIR" >&2; exit 1; }
  real_sum="$REAL_INITDIR/$(basename "$sum")"

  mirror_odf_into_init
  "$PYTHON" "$SCRIPT_DIR/tools.py" rewrite-path "$sum" "$REAL_INITDIR/"
  write_sas_setup "$real_sum"
  echo "Wrote $REAL_WORKDIR/sas_setup.env"
  [[ "$PRINT_ENV" == "1" ]] && print_env
}

write_manifest() {
  local outfile="$1" root="$2" tmp
  shift 2
  tmp="${outfile}.tmp.$$"
  mkdir -p "$(dirname "$outfile")"

  shopt -s globstar nullglob
  for pattern in "$@"; do
    for f in "$root"/**/$pattern; do
      [[ -f "$f" ]] && readlink -f "$f"
    done
  done | awk '!seen[$0]++' > "$tmp"

  if [[ -s "$tmp" || ! -e "$outfile" ]]; then
    if [[ -e "$outfile" ]] && cmp -s "$tmp" "$outfile"; then
      rm -f "$tmp"
    else
      mv -f "$tmp" "$outfile"
    fi
  else
    rm -f "$tmp"
  fi
}

write_raw_manifests() {
  local inst
  for inst in $DETECTORS; do
    case "$inst" in
      PN) write_manifest "$REPRODIR/manifest/PN_raw.txt" "$REPRODIR" '*EPN*ImagingEvts.ds' '*EPN*ImagingEvts*.FIT*' '*PIEVLI*.FIT*' '*EPN*EVLI*.FIT*' ;;
      M1) write_manifest "$REPRODIR/manifest/M1_raw.txt" "$REPRODIR" '*EMOS1*ImagingEvts.ds' '*EMOS1*ImagingEvts*.FIT*' '*M1EVLI*.FIT*' '*EMOS1*EVLI*.FIT*' ;;
      M2) write_manifest "$REPRODIR/manifest/M2_raw.txt" "$REPRODIR" '*EMOS2*ImagingEvts.ds' '*EMOS2*ImagingEvts*.FIT*' '*M2EVLI*.FIT*' '*EMOS2*EVLI*.FIT*' ;;
    esac
  done
}

manifest_paths_exist() {
  local manifest="$1" path have=0
  [[ -s "$manifest" ]] || return 1
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    [[ -s "$path" ]] || return 1
    have=1
  done < "$manifest"
  [[ "$have" == "1" ]]
}

repro_products_ready() {
  local inst
  for inst in $DETECTORS; do
    manifest_paths_exist "$REAL_REPRODIR/manifest/${inst}_raw.txt" || return 1
  done
  [[ -s "$REAL_REPRODIR/atthk.dat" && -s "$REAL_WORKDIR/attitude.env" ]]
}

drop_stale_manifests() {
  local inst manifest
  for inst in $DETECTORS; do
    manifest="$REAL_REPRODIR/manifest/${inst}_raw.txt"
    [[ -e "$manifest" ]] || continue
    manifest_paths_exist "$manifest" || rm -f "$manifest"
  done
}

choose_original_ahf() {
  local pattern found
  for pattern in '*SC*ATS.FIT*' '*SC*ATS.FT*' '*ATS.FIT*' '*ATS.FT*' '*ATTTSR*.FIT*' '*AHF*.FIT*'; do
    found="$(find "$ODFDIR" -type f -name "$pattern" | sort)"
    found="${found%%$'\n'*}"
    [[ -n "$found" ]] && { readlink -f "$found"; return 0; }
  done
  return 1
}

write_attitude_env() {
  local ahf="$AHF_INPUT"
  [[ -n "$ahf" ]] || ahf="$(choose_original_ahf)" || {
    echo "Could not locate an original spacecraft attitude file in $ODFDIR" >&2
    exit 1
  }
  [[ -f "$ahf" ]] || { echo "AHF/ATS file not found: $ahf" >&2; exit 1; }

  {
    printf 'ATTHKGEN_FILE=%q\n' "$REAL_REPRODIR/atthk.dat"
    printf 'ATTHK_FILE=%q\n' "$REAL_REPRODIR/atthk.dat"
    printf 'AHF_FILE=%q\n' "$ahf"
  } | write_if_changed "$REAL_WORKDIR/attitude.env"
}

stage_repro() {
  if ! init_products_ready; then
    stage_init
  else
    adopt_existing_init
  fi

  mkdir -p "$REPRODIR/manifest"
  if [[ "$FORCE" == "1" ]]; then
    rm -f "$REPRODIR/manifest/"*_raw.txt "$REPRODIR/atthk.dat" "$REAL_WORKDIR/attitude.env"
  else
    drop_stale_manifests
  fi
  write_raw_manifests

  if [[ "$FORCE" != "1" ]] && repro_products_ready; then
    echo "Skipping repro; found existing raw manifests, atthk.dat, and attitude.env"
    return 0
  fi

  set_sas_repro_env
  need_cmd atthkgen

  pushd "$REPRODIR" >/dev/null

  local want_pn=0 want_mos=0 inst pn_ready=0 mos_ready=1
  for inst in $DETECTORS; do
    [[ "$inst" == "PN" ]] && want_pn=1
    if [[ "$inst" == "M1" || "$inst" == "M2" ]]; then
      want_mos=1
      manifest_paths_exist "$REAL_REPRODIR/manifest/${inst}_raw.txt" || mos_ready=0
    fi
  done
  manifest_paths_exist "$REAL_REPRODIR/manifest/PN_raw.txt" && pn_ready=1

  if [[ "$want_pn" == "1" && ( "$FORCE" == "1" || "$pn_ready" == "0" ) ]]; then
    need_cmd epproc
    runlog repro_epproc epproc
  fi
  if [[ "$want_mos" == "1" && ( "$FORCE" == "1" || "$mos_ready" == "0" ) ]]; then
    need_cmd emproc
    runlog repro_emproc emproc
  fi

  write_raw_manifests
  for inst in $DETECTORS; do
    manifest_paths_exist "$REAL_REPRODIR/manifest/${inst}_raw.txt" || {
      echo "No selected $inst imaging event lists found after repro" >&2
      exit 1
    }
  done

  if [[ "$FORCE" == "1" || ! -s "$REPRODIR/atthk.dat" ]]; then
    runlog repro_atthkgen atthkgen atthkset="$REPRODIR/atthk.dat"
  fi
  popd >/dev/null

  write_attitude_env
  echo "Wrote $REAL_WORKDIR/attitude.env"
}

clean_gti_enabled() {
  is_yes "${CLEAN_GTI_ENABLED:-yes}"
}

clean_band_labels() {
  "$PYTHON" "$SCRIPT_DIR/tools.py" clean-band-labels "$CONFIG"
}

clean_expr() {
  "$PYTHON" "$SCRIPT_DIR/tools.py" clean-expr "$CONFIG" "$1" "$2"
}

flare_lc_expr() {
  local inst="$1" qual
  if [[ "$inst" == "PN" ]]; then
    qual="(FLAG==0)"
  else
    qual="#XMMEA_EM"
  fi
  echo "(PATTERN<=$CLEAN_GTI_PATTERN_MAX)&&(PI in [$CLEAN_GTI_PI_MIN:$CLEAN_GTI_PI_MAX])&&$qual"
}

build_flare_gti() {
  local inst="$1" evt="$2" base="$3"
  local lc gti expr lc_real gti_real
  mkdir -p "$LIGHTCURVEDIR/$inst" "$GTIDIR/$inst"

  lc="$LIGHTCURVEDIR/$inst/${base}_flare_lc.fits"
  gti="$GTIDIR/$inst/${base}_flare_gti.fits"
  if [[ "$FORCE" == "1" || ! -s "$gti" ]]; then
    expr="$(flare_lc_expr "$inst")"
    runlog "lc_${inst}_${base}" \
      evselect table="${evt}:EVENTS" withrateset=yes rateset="$lc" \
        maketimecolumn=yes timecolumn=TIME timebinsize="$CLEAN_GTI_TIMEBIN" \
        makeratecolumn=yes expression="$expr"
    runlog "gti_${inst}_${base}" \
      tabgtigen table="${lc}:RATE" gtiset="$gti" expression="RATE <= $CLEAN_GTI_RATE_CUT"
  fi

  lc_real="$(readlink -f "$lc" 2>/dev/null || echo "$lc")"
  gti_real="$(readlink -f "$gti" 2>/dev/null || echo "$gti")"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$inst" "$base" "$CLEAN_GTI_RATE_CUT" "$CLEAN_GTI_TIMEBIN" "$CLEAN_GTI_PI_MIN" "$CLEAN_GTI_PI_MAX" "$lc_real" "$gti_real" >> "$GTI_SUMMARY"
  CLEAN_GTI_RESULT="$gti"
}

clean_manifest_valid() {
  local manifest="$1" path
  [[ -f "$manifest" ]] || return 1
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    [[ -s "$path" ]] || return 1
  done < "$manifest"
}

clean_manifest_for_detector() {
  local inst="$1" candidate
  for candidate in "$REAL_CLEANDIR/manifest/${inst}_clean_files.txt" "$REAL_CLEANDIR/${inst}_clean_files.txt"; do
    if manifest_paths_exist "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

clean_stage_complete() {
  local inst label manifest legacy
  if [[ -s "$REAL_CLEANDIR/.complete" ]]; then
    for inst in $DETECTORS; do
      while IFS= read -r label; do
        [[ -n "$label" ]] || continue
        manifest="$REAL_CLEANDIR/manifest/${inst}_${label}_clean_files.txt"
        clean_manifest_valid "$manifest" || return 1
      done < <(clean_band_labels)
    done
    return 0
  fi

  for inst in $DETECTORS; do
    legacy="$(clean_manifest_for_detector "$inst" || true)"
    [[ -n "$legacy" ]] || return 1
  done
}

write_clean_band_manifest() {
  local inst="$1" label="$2" out="$CLEANDIR/manifest/${inst}_${label}_clean_files.txt"
  mkdir -p "$CLEANDIR/manifest"
  {
    if [[ -d "$CLEANDIR/events/$inst/$label" ]]; then
      find "$CLEANDIR/events/$inst/$label" -maxdepth 1 -type f -name '*_clean.fits' | sort | while IFS= read -r path; do
        readlink -f "$path"
      done
    fi
  } | write_if_changed "$out"
}

write_clean_manifest() {
  local inst="$1" out="$CLEANDIR/manifest/${inst}_clean_files.txt"
  mkdir -p "$CLEANDIR/manifest"
  {
    if [[ -d "$CLEANDIR/events/$inst" ]]; then
      find "$CLEANDIR/events/$inst" -type f -name '*_clean.fits' | sort | while IFS= read -r path; do
        readlink -f "$path"
      done
    fi
  } | write_if_changed "$out"
}

clean_one_event() {
  local inst="$1" evt="$2" label="$3" outfile="$4" gti="$5"
  local expr rows

  if [[ "$FORCE" != "1" && -s "$outfile" ]]; then
    return 0
  fi

  expr="$(clean_expr "$inst" "$label")"
  if [[ -n "$gti" ]]; then
    expr="($expr)&&gti($gti,TIME)"
  fi

  runlog "clean_${inst}_${label}_$(basename "${outfile%.fits}")" \
    evselect table="${evt}:EVENTS" \
      withfilteredset=yes filteredset="$outfile" \
      destruct=yes keepfilteroutput=yes updateexposure=yes writedss=yes \
      expression="$expr"

  rows="$("$PYTHON" "$SCRIPT_DIR/tools.py" fits-rows "$outfile")"
  if [[ "$rows" -le 0 ]]; then
    echo "No events left after cleaning: $outfile" >&2
    rm -f "$outfile"
    return 0
  fi

  attcalc eventset="$outfile" attitudelabel=ahf refpointlabel=pnt withatthkset=yes atthkset="$ATTHKGEN_FILE"
}

stage_clean() {
  local inst label rawlist evt base gti outfile
  local labels=()

  if ! repro_products_ready; then
    stage_repro
  fi

  if [[ "$FORCE" != "1" ]] && clean_stage_complete; then
    echo "Skipping clean; found existing clean products in $REAL_WORKDIR/clean"
    return 0
  fi

  while IFS= read -r label; do
    [[ -n "$label" ]] && labels+=("$label")
  done < <(clean_band_labels)
  [[ "${#labels[@]}" -gt 0 ]] || { echo "No clean bands configured" >&2; exit 1; }

  set_sas_clean_env
  need_cmd evselect
  need_cmd attcalc
  clean_gti_enabled && need_cmd tabgtigen

  if [[ "$FORCE" == "1" ]]; then
    shopt -s nullglob
    rm -f "$CLEANDIR/.complete" "$CLEANDIR/clean_band_filters.tsv" "$CLEANDIR/manifest/"*_clean_files.txt
    rm -f "$CLEANDIR/events/"*/*_clean.fits "$CLEANDIR/events/"*/*/*_clean.fits
    rm -f "$GTIDIR/"*/*_flare_gti.fits "$LIGHTCURVEDIR/"*/*_flare_lc.fits
    shopt -u nullglob
  fi

  mkdir -p "$CLEANDIR/manifest"
  "$PYTHON" "$SCRIPT_DIR/tools.py" clean-band-table "$CONFIG" > "$CLEANDIR/clean_band_filters.tsv"
  if clean_gti_enabled; then
    mkdir -p "$GTIDIR" "$LIGHTCURVEDIR"
    printf 'inst\tevent\trate_cut_ct_s\ttimebin_s\tpi_min\tpi_max\tlightcurve\tgti\n' > "$GTI_SUMMARY"
  fi

  for inst in $DETECTORS; do
    rawlist="$REAL_REPRODIR/manifest/${inst}_raw.txt"
    manifest_paths_exist "$rawlist" || { echo "Missing or stale raw manifest: $rawlist" >&2; exit 1; }

    while IFS= read -r evt; do
      [[ -n "$evt" ]] || continue
      base="$(basename "$evt")"
      base="${base%.*}"
      gti=""
      if clean_gti_enabled; then
        CLEAN_GTI_RESULT=""
        build_flare_gti "$inst" "$evt" "$base"
        gti="$CLEAN_GTI_RESULT"
      fi

      for label in "${labels[@]}"; do
        mkdir -p "$CLEANDIR/events/$inst/$label"
        outfile="$CLEANDIR/events/$inst/$label/${base}_${label}_clean.fits"
        clean_one_event "$inst" "$evt" "$label" "$outfile" "$gti"
      done
    done < "$rawlist"

    for label in "${labels[@]}"; do
      write_clean_band_manifest "$inst" "$label"
    done
    write_clean_manifest "$inst"
  done

  date -u +%FT%TZ > "$CLEANDIR/.complete"
  echo "Wrote $REAL_CLEANDIR/clean_band_filters.tsv"
  echo "Wrote $REAL_CLEANDIR/manifest"
}

file_type() {
  local name="$1"
  case "$name" in
    *SUM.SAS) echo "SUM.SAS" ;;
    ccf.cif) echo "ccf.cif" ;;
    *.FIT|*.FTZ|*.fits|*.fits.gz) echo "FITS" ;;
    *.ASC) echo "ASC" ;;
    MANIFEST.*) echo "MANIFEST" ;;
    *.ds) echo "ds" ;;
    *.*) echo "${name##*.}" ;;
    *) echo "other" ;;
  esac
}

count_lines() {
  [[ -s "$1" ]] && wc -l < "$1" || echo 0
}

qc_init() {
  local qcdir="$WORKDIR/qc/init" files="$WORKDIR/qc/init/output_files.txt"
  local counts="$WORKDIR/qc/init/file_type_counts.txt"
  [[ -d "$INITDIR" ]] || { echo "Missing init output directory: $INITDIR" >&2; exit 1; }
  mkdir -p "$qcdir"

  {
    [[ -f "$REAL_WORKDIR/sas_setup.env" ]] && echo "$REAL_WORKDIR/sas_setup.env"
    [[ -d "$LOGDIR" ]] && find "$LOGDIR" -maxdepth 1 -type f -name 'init_*.log' | sort
    find "$INITDIR" -maxdepth 1 \( -type f -o -type l \) | sort
  } > "$files"

  while IFS= read -r path; do
    file_type "$(basename "$path")"
  done < "$files" | sort | uniq -c | awk '{ printf "%s %s\n", $2, $1 }' > "$counts"

  echo "Wrote $files"
  echo "Wrote $counts"
}

qc_repro() {
  local qcdir="$WORKDIR/qc/repro" files="$WORKDIR/qc/repro/output_files.txt"
  local counts="$WORKDIR/qc/repro/manifest_counts.txt" status="$WORKDIR/qc/repro/status.txt"
  local inst
  [[ -d "$REPRODIR" ]] || { echo "Missing repro output directory: $REPRODIR" >&2; exit 1; }
  mkdir -p "$qcdir"

  {
    [[ -f "$REAL_WORKDIR/attitude.env" ]] && echo "$REAL_WORKDIR/attitude.env"
    [[ -d "$LOGDIR" ]] && find "$LOGDIR" -maxdepth 1 -type f -name 'repro_*.log' | sort
    find "$REPRODIR" -maxdepth 2 \( -type f -o -type l \) | sort
  } > "$files"

  {
    for inst in $DETECTORS; do
      echo "$inst $(count_lines "$REAL_REPRODIR/manifest/${inst}_raw.txt")"
    done
  } > "$counts"

  {
    [[ -s "$REAL_REPRODIR/atthk.dat" ]] && echo "atthk.dat ok" || echo "atthk.dat missing"
    [[ -s "$REAL_WORKDIR/attitude.env" ]] && echo "attitude.env ok" || echo "attitude.env missing"
    for inst in $DETECTORS; do
      manifest_paths_exist "$REAL_REPRODIR/manifest/${inst}_raw.txt" && echo "${inst}_raw.txt ok" || echo "${inst}_raw.txt missing_or_stale"
    done
  } > "$status"

  rm -f "$qcdir"/soft*_mosaic.png "$qcdir"/hard*_mosaic.png
  "$PYTHON" "$SCRIPT_DIR/tools.py" event-mosaic "$REAL_REPRODIR/manifest" "$qcdir" "$DETECTORS" "$QC_SOFT_HARD_SPLIT_EV"

  echo "Wrote $files"
  echo "Wrote $counts"
  echo "Wrote $status"
  echo "Wrote $qcdir/soft_mosaic.png"
  echo "Wrote $qcdir/hard_mosaic.png"
}

qc_clean() {
  local qcdir="$WORKDIR/qc/clean" files="$WORKDIR/qc/clean/output_files.txt"
  local counts="$WORKDIR/qc/clean/manifest_counts.txt" status="$WORKDIR/qc/clean/status.txt"
  local inst label manifest legacy
  [[ -d "$CLEANDIR" ]] || { echo "Missing clean output directory: $CLEANDIR" >&2; exit 1; }
  mkdir -p "$qcdir"

  {
    find "$CLEANDIR" -maxdepth 5 \( -type f -o -type l \) | sort
    [[ -d "$LOGDIR" ]] && find "$LOGDIR" -maxdepth 1 -type f \( -name 'clean_*.log' -o -name 'lc_*.log' -o -name 'gti_*.log' \) | sort
  } > "$files"

  {
    for inst in $DETECTORS; do
      while IFS= read -r label; do
        [[ -n "$label" ]] || continue
        manifest="$REAL_CLEANDIR/manifest/${inst}_${label}_clean_files.txt"
        echo "$inst $label $(count_lines "$manifest")"
      done < <(clean_band_labels)
      legacy="$(clean_manifest_for_detector "$inst" || true)"
      [[ -n "$legacy" ]] && echo "$inst aggregate $(count_lines "$legacy")"
    done
  } > "$counts"

  {
    if clean_stage_complete; then
      echo "clean_stage complete"
    else
      echo "clean_stage missing_or_stale"
    fi
    for inst in $DETECTORS; do
      while IFS= read -r label; do
        [[ -n "$label" ]] || continue
        manifest="$REAL_CLEANDIR/manifest/${inst}_${label}_clean_files.txt"
        clean_manifest_valid "$manifest" && echo "${inst}_${label}_clean_files.txt ok" || echo "${inst}_${label}_clean_files.txt missing_or_stale"
      done < <(clean_band_labels)
      legacy="$(clean_manifest_for_detector "$inst" || true)"
      [[ -n "$legacy" ]] && echo "$(basename "$legacy") legacy_or_aggregate_ok"
    done
  } > "$status"

  [[ -s "$CLEANDIR/clean_band_filters.tsv" ]] && cp -f "$CLEANDIR/clean_band_filters.tsv" "$qcdir/clean_band_filters.tsv"
  [[ -s "$CLEANDIR/flare_gti_summary.tsv" ]] && cp -f "$CLEANDIR/flare_gti_summary.tsv" "$qcdir/flare_gti_summary.tsv"

  rm -f "$qcdir"/soft*_mosaic.png "$qcdir"/hard*_mosaic.png
  "$PYTHON" "$SCRIPT_DIR/tools.py" event-mosaic "$REAL_CLEANDIR" "$qcdir" "$DETECTORS" "$QC_SOFT_HARD_SPLIT_EV"

  echo "Wrote $files"
  echo "Wrote $counts"
  echo "Wrote $status"
  [[ -s "$qcdir/clean_band_filters.tsv" ]] && echo "Wrote $qcdir/clean_band_filters.tsv"
  [[ -s "$qcdir/flare_gti_summary.tsv" ]] && echo "Wrote $qcdir/flare_gti_summary.tsv"
  echo "Wrote $qcdir/soft_mosaic.png"
  echo "Wrote $qcdir/hard_mosaic.png"
}

run_qc_stage() {
  case "$1" in
    init) qc_init ;;
    repro) qc_repro ;;
    clean) qc_clean ;;
    all|qc) qc_init; qc_repro; qc_clean ;;
    *) echo "No QC stage for: $1" >&2; exit 2 ;;
  esac
}

maybe_run_qc() {
  [[ "$RUN_QC" == "1" ]] || return 0
  run_qc_stage "$STAGE"
}

case "$STAGE" in
  init) stage_init; maybe_run_qc ;;
  repro) stage_repro; maybe_run_qc ;;
  clean) stage_clean; maybe_run_qc ;;
  all) stage_init; stage_repro; stage_clean; maybe_run_qc ;;
  qc-init) qc_init ;;
  qc-repro) qc_repro ;;
  qc-clean) qc_clean ;;
  qc) run_qc_stage all ;;
  env) print_env ;;
  *) echo "Unknown stage: $STAGE" >&2; exit 2 ;;
esac
